[parity]
chain = "demo-spec.json"
base_path = "/Users/reza/projects/parity-training/parity2"
[network]
port = 30303
[rpc]
port = 8543
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
[ui]
port = 8183
[websockets]
port = 8453
[ipc]
disable = true